version: 0.0
os: linux
files:
  - source: target/ByteBazaar-0.0.1-SNAPSHOT.jar
    destination: /opt/bytebazaar/
    overwrite: yes
  - source: scripts/
    destination: /opt/bytebazaar/scripts/
    overwrite: yes
permissions:
  - object: /opt/bytebazaar/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
  - object: /opt/bytebazaar/scripts/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: ec2-user
